### ISSUE TITLE
Optifine and Bits breaking?

### ISSUE THREAD

**Issue by ChaaLik** [Aeltumn/Chisels-and-Bits-2#17] opened 2019-11-28 18:56 UTC
So I used the chisel mod and everything was going fine, but it was incredibly laggy as I removed more blocks. It seems to go away when I'm not selecting/highlighting with the chisel. That seems to be the only problem for my side at least, however I have yet to investigate the mod much deeper. So after this, I installed Optifine to reduce the lag. I go on the game and the block has colored lines that drift away from the block I chiseled. Investigating further, it happens when a bit is added or removed. Any bit whether air or a normal block seems to just kinda break. It goes invisible and the entire thing bugs out with those colored spikes coming off of them. This has only occurred when I added optifine in however, so not sure what that's about, it might be worth looking into.

**Comment by DarkOrpheus001** [comment] 2019-11-28 22:02
I also noticed the lags. The more I chisel the more laggy it gets. As i remove the Bit Bag and replace it with a new one the FPS get normal again. The lag only occurs while the Bit Bag or The Chisel is selected and while i'm in the inventory. (Don't know much about coding, but my guess is that there's some error with the saving of the content from the Bit Bag?)

**Comment by Aeltumn** [comment] 2019-11-28 23:50
Currently, Optifine is not supported at all. I haven't tested the mod with Optifine at all but I will fix compatibility in a future alpha. For now, I'll mark using Optifine with C&B2 having issues as working as intended, but do know that this will be fixed in the future!
The performance is currently pretty bad and I will dedicate entire future alphas/betas to solely performance improvements. So, for now I will mark this issue as won't fix but that's just because this isn't a priority at the moment.

**Closed by Aeltumn** 2019-11-28 23:50 UTC
