### ISSUE TITLE
Dropping bit crashes game

### ISSUE THREAD

**Issue by Floffah** [Aeltumn/Chisels-and-Bits-2#49] opened 2020-05-31 15:02 UTC
Forge: 1.14.1-forge-28.2.17

When I drop a bit (i tried it on a quartz bit from the creative tab), it crashes the game and because it stays there when i open the game again, I can't get into the world

```
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world
```

Crash report: [click here](https://pastebin.com/F3GExqm2)

Looking at that error it seems there is an issue with Mr Crayfish's Obfuscate mod when use with this mod

However, when removing that mod I now get [this error](https://pastebin.com/79pbYDmp)

**Comment by Aeltumn** [comment] 2020-05-31 16:17
Duplicate of #40

**Closed by Aeltumn** 2020-05-31 16:17 UTC
Labels: duplicate
