### ISSUE TITLE
Graphic bug with shader on

### ISSUE THREAD

**Issue by isuckatbuilding** [Aeltumn/Chisels-and-Bits-2#69] opened 2020-10-08 12:05 UTC
If a block is being chiselled the block's graphic will completely bugged.
And if no shader it works normal.
Any solution?

Also can we have a complete instructions for using this mod, plz?

**Comment by Aeltumn** [comment] 2020-10-08 12:18
Duplicate of #34, the mod is not compatible with shaders at the moment.

**Closed by Aeltumn** 2020-10-08 12:18 UTC
